### ISSUE TITLE
Auto backup prune not working

### ISSUE THREAD

**Issue by exptom** [voxpupuli/puppet-stash#91] opened 2015-09-17 08:52 UTC
No matter what value I give to backup_keep_age it never seems to run!
I have stash::backup_keep_age: '5d' set in hiera am I missing something obvious?

**Comment by igalic** [comment] 2015-09-21 16:55
i've experienced similar failures and chalked it up to my own misconfiguration. i was obviously wrong.

i have no idea why it's not doing what the documentation says it should be doing.
/cc @ffrank

**Comment by mkrakowitzer** [comment] 2015-09-22 20:29
I'll look into it, I have a different backup strategy so I have not picked it up :/

**Comment by ffrank** [comment] 2015-09-23 22:09
Will gladly take a crack at it, but am thoroughly booked until PuppetConf.

Perhaps we can form an ad hoc task force at some point in Portland.

**Comment by ffrank** [comment] 2015-10-06 01:11
I assume this works as designed. It may well be confusing because often, changing the value will not yield a sync action by the agent, because it only controls a [tidy](https://github.com/puppet-community/puppet-stash/blob/e4b5fb1248354049146e6560cfb6938d75987573/manifests/backup.pp#L97-L103) resource.

This resource will only sync if the agent machine happens to have matching files in the backup directory.

@mkrakowitzer would it be more sensible to manage a good old `find ... -delete` cron job here instead of the `tidy`? Doing backup lifecycle management through the Puppet agent feels a little unclean to me in either case.

**Comment by igalic** [comment] 2015-10-13 14:51
@ffrank thanks for the analysis!
we shall patch this then.

**Comment by mkrakowitzer** [comment] 2015-10-13 16:14
Before we do that, I would like to get the bottom of why this does not work. In theory this should function just fine and clean up any old backup files that match in the given directory. 

The behavior that @igalic and @exptom are experiencing does not match this. Their experience is that nothing is being removed from the backup directories. 

@igalic I will look into this before the end of the week (Even if just to satisfy my curiosity), thereafter we can proceed with @ffrank's suggestion of the cron job?

**Comment by ffrank** [comment] 2015-10-13 18:13
:+1:

**Comment by johnlawerance** [comment] 2015-10-14 19:48
This isn't working because the actual backups are performed in ${backup_home}/archives/backups/ and tidy is set to only recurse once. Fixed in [PR 100](https://github.com/puppet-community/puppet-stash/pull/100)

**Comment by mkrakowitzer** [comment] 2015-10-14 19:56
@johnlawerance Thanks! Saved me having to investigate this!

**Comment by johnlawerance** [comment] 2015-10-21 16:22
Closed previous PR due to conflicts. Created new one: [PR 102](https://github.com/puppet-community/puppet-stash/pull/102)

**Comment by mkrakowitzer** [comment] 2015-10-21 16:27
Thanks John.

**Closed as completed by mkrakowitzer** 2015-10-21 16:27 UTC

**Comment by exptom** [comment] 2015-10-23 10:12
Thanks for everybody’s help with this issue.
I'm trying to test it but have some issues. I've switched from 1.3.0 to master branch in my Puppetfile but librarian is complaining that the puppet-staging dependency doesn't exist.
Are you able to release a forge version that includes this fix?

**Comment by mkrakowitzer** [comment] 2015-10-23 10:42
This fix wont be available until the 2.0.0 release. 'Ill try get it out as soon as I can but work commitments are getting in the way :(

**Comment by exptom** [comment] 2015-10-23 10:56
No problem. I have forked, branched off of 1.3 and applied the recurse fix and can confirm it is working correctly on my server. It might also be worth adding pruning for backup log files too?
